appName = "monitor"

# App run mode:
# 1. dev(default)
# 2. prod
runMode = "dev"

[node]
dataFile = "nodes.json"

[influxdb]
address = "http://localhost:8086"
username = "root"
password = "root"
database = "tronmonitor"

[log]
filename = "monitor.log"

# Log level:
# 1. emergency
# 2. alert
# 3. critical
# 4. error
# 5. warning
# 6. notice
# 7. information
# 8. debug(default)
level = "debug"

[http]
port = 8080

[task]
# Interval defalut 60 seconds
getDataInterval = 60
dingding = "https://oapi.dingtalk.com/robot/send?access_token=06e2dbc217811edaad00b5c684597902bf05a457a60759b5d3b3f249e0de9db7"